Feature: Plan change API
hiqdev/billing-hiapi pull request #23
Opened 2021-03-12 16:07 UTC by SilverFire

2021-03-15 15:40 UTC, strorch commented on src/sale/Close/SaleCloseAction.php
> +use DateTime;
лишній юз

2021-03-15 15:44 UTC, SilverFire commented on src/sale/Close/SaleCloseAction.php
> +use DateTime;
```suggestion
```

2021-03-15 15:45 UTC, SilverFire commented on src/sale/Create/Builder.php
> +namespace hiqdev\billing\hiapi\sale\ChangePlan;
```suggestion
namespace hiqdev\billing\hiapi\sale\Create;
```

2021-03-17 07:49 UTC, tafid approved these changes

2021-03-17 12:07 UTC, hiqsol commented on src/target/ChangePlan/Action.php
> +class Action
Из всего ПРа ревьювить надо только этот класс.
Почитал-почитал - вроде норм.
Единственная мысль - может это ответственность модели (php-billing)?

2021-03-17 12:32 UTC, SilverFire commented on src/target/ChangePlan/Action.php
> +class Action
Обсудили голосом

2021-03-17 12:47 UTC, strorch commented on src/sale/Search/BulkAction.php
> +        if (in_array('history', $command->include, true)) {
$res = in_array('history', $command->include, true) 
            ? $this->historyRepo->findAll($specification)
            : $this->repo->findAll($specification);

2021-03-17 12:53 UTC, strorch requested changes

2021-03-17 12:53 UTC, strorch commented on src/sale/Search/CountAction.php
> +        if (in_array('history', $command->include, true)) {
ця перевірка 2 раза в коді зустрілась

2021-03-17 12:53 UTC, strorch commented on src/sale/Search/BulkAction.php
> +        if (in_array('history', $command->include, true)) {
$res = in_array('history', $command->include, true) 
        ? $this->historyRepo->findAll($specification)
        : $this->repo->findAll($specification);

2021-03-17 12:53 UTC, strorch commented on src/target/ChangePlan/Action.php
> +            $this->connection->transaction(function () use ($activeSale, $sale) {
try {
            $this->connection->transaction(function () use ($newSale, $activeSale) {
                $this->saleRepo->delete($activeSale);
                $this->saleRepo->save($newSale);
            });
        } catch (Throwable $exception) {
            $this->log->error('Failed to change scheduled plan change', ['exception' => $exception]);
            throw new RuntimeException('Failed to change scheduled plan change');
        }
        

3 раза цей код

2021-03-17 12:57 UTC, SilverFire commented on src/sale/Search/BulkAction.php
> +        if (in_array('history', $command->include, true)) {
засылай такое в виде `suggestion`'ов, плз

2021-03-17 12:58 UTC, SilverFire commented on src/sale/Search/CountAction.php
> +        if (in_array('history', $command->include, true)) {
Как бы ты это исправил?

2021-03-17 13:07 UTC, SilverFire commented on src/target/ChangePlan/Action.php
> +            $this->connection->transaction(function () use ($activeSale, $sale) {
https://github.com/hiqdev/billing-hiapi/pull/23/commits/3bdaf41d05973f5a2bad7593df26c8c488135a04

Исправил вот так. Третий раз – там `Delete`.

2021-03-17 13:25 UTC, strorch commented on src/sale/Search/CountAction.php
> +        if (in_array('history', $command->include, true)) {
виніс би в абстракний клас з методом , який вертає об*єкт репозиторія

2021-03-17 13:26 UTC, strorch commented on src/sale/Search/CountAction.php
> +        if (in_array('history', $command->include, true)) {
і якраз лаконічно в цей метод впишеться ретурн з тернарніком

2021-03-17 13:40 UTC, merged