Feature. Add permission check after the checks in the builders have b…
hiqdev/billing-hiapi pull request #30
Opened 2021-09-03 06:22 UTC by tafid

…een removed

2021-09-03 07:44 UTC, strorch approved these changes

2021-09-06 11:20 UTC, SilverFire requested changes

2021-09-06 11:20 UTC, SilverFire commented on src/tools/PermissionCheckerInterface.php
> +    public function ensureCustomerCan(CustomerInterface $customer, $permission): void;
```suggestion
    public function ensureCustomerCan(CustomerInterface $customer, string $permission): void;
```

Или ты тут умышленно не добавлял тип?

+ нужно описать, какой Exception ожидать если не получится

2021-09-06 11:20 UTC, SilverFire commented on src/tools/PermissionCheckerInterface.php
> +    public function getRoles($clientId): array;
```suggestion
```

Мы не проверяем роли. Зачем делать это частью публичного API?

2021-09-06 11:20 UTC, SilverFire commented on src/tools/PermissionCheckerInterface.php
> +    public function checkAccess($clientId, string $permission): bool;
`$clientId` специально не типизированный? Почему?

Я немного не согласен с названием метода. **checkAccess** = **проверитьДоступ**.

Доступ проверяют к какой-то странице, а тут проверяется наличие права как такового. Я бы переименовал.

2021-09-06 11:21 UTC, SilverFire commented on src/tools/PermissionCheckerInterface.php
> +    public function checkAccess($clientId, string $permission): bool;
Ты, наверное, назвал как в `yii\rbac\CheckAccessInterface`, но там суть в том, что есть третий параметр `$params` – это для рулей и ABAC, тогда название более оправдано.

2021-09-06 11:26 UTC, SilverFire commented
Тут нет дефолтной реализации интерфейса, получается этот пакет и все его Action'ы не будут работать, пока не подключишь пакет с реализацией.

Я не уверен, что это ок @hiqsol

2021-09-06 11:44 UTC, hiqsol commented on src/tools/PermissionCheckerInterface.php
> +    public function checkAccess($clientId, string $permission): bool;
так а как ты предлагаешь `checkPermission` или просто `can` ?

2021-09-09 11:30 UTC, tafid commented on src/tools/PermissionCheckerInterface.php
> +    public function checkAccess($clientId, string $permission): bool;
1.  Одна из причин почему я намерено не типизировал $clientId - потому что \hiqdev\php\billing\customer\Сustomer::getId() не типизированно
2. checkAccess выбран потому что в Yii именно эта функция вызывается на данную операцию, т.ё. когда мы делаем user->can()

2021-09-14 07:43 UTC, strorch approved these changes

2021-09-20 10:33 UTC, merged