HP-897 refactor change plan to set new buyer from `customer_id`
hiqdev/billing-hiapi pull request #64
Opened 2022-07-26 06:38 UTC by tafid

2022-07-29 15:09 UTC, SilverFire requested changes

2022-07-29 15:09 UTC, SilverFire commented on src/target/ChangePlan/Action.php
> +        public ActiveSaleFinder $activeSaleFinder
```suggestion
        private ActiveSaleFinder $activeSaleFinder
```

2022-07-29 15:09 UTC, SilverFire commented on src/target/ChangePlan/Command.php
> +            [['check_belonging'], 'boolean'],
это позволит назначать свойство с запроса от юзера. Кажется, тут может быть уязвимость

2022-07-29 15:14 UTC, tafid commented on src/target/ChangePlan/Action.php
> +        public ActiveSaleFinder $activeSaleFinder
Ну может можно потом и через сетер его менять. Закрыть и добавить сетер?

2022-08-03 11:14 UTC, SilverFire requested changes

2022-08-03 11:14 UTC, SilverFire commented on src/target/ChangePlan/Action.php
> +        if ($command->check_belonging === true) {
```suggestion
        if ($command->check_belonging) {
```

Там булево свойство, этого достаточно

2022-08-03 11:14 UTC, SilverFire commented on src/target/ChangePlan/Command.php
> +            [['check_belonging'], 'boolean'],
что будет, если я передам это свойство с запросом?

2022-08-04 12:22 UTC, tafid commented on src/target/ChangePlan/Command.php
> +            [['check_belonging'], 'boolean'],
изменил

2022-08-04 12:25 UTC, hiqsol commented on src/target/ChangePlan/Action.php
> +        private ActiveSaleFinder $activeSaleFinder
чтоб не было дифов в одну запятую - ставь запятую после последнего аргумента тоже

2022-08-04 12:25 UTC, hiqsol approved these changes

2022-08-10 11:09 UTC, merged